### ISSUE TITLE
Something wrong (different number of reads written and reads that should be written)

### ISSUE THREAD

**Issue by nailabc** [yhwu/idemp#7]
Hi, I am performing the demultiplex for a Illumina Miseq 16S rRNA run (V4 region, paired reads) and I got a warning message like the one below for all my samples. It seems that it was not possible to write the correct number of reads per barcode. Any thoughts of why this could be happening?

5 reads should be written to /Users/Naila/Desktop/16S_glyphosate/demultiplex2/Undetermined_S0_L001_R1_001_out.fastq_negative.control.fastq.gz
2 reads were written

**Comment by yhwu** [comment]
without a piece of your data, it's tell what's the cause.

**Comment by nailabc** [comment]
In fact the input files had a problem. I solved it, thanks!
